version: "2"

linters:
  enable:
  - govet
  - errcheck
  - staticcheck
  - ineffassign
  - misspell
  - gocritic
  - revive
  - gosec
  - nolintlint
  - gocyclo
  exclusions:
    warn-unused: true
    presets:
    - std-error-handling
    - common-false-positives
