version: "2"

linters:
  enable:
  - errcheck
  - gocritic
  - gocyclo
  - gosec
  - govet
  - ineffassign
  - misspell
  - nolintlint
  - revive
  - staticcheck
  - usetesting
  - wsl_v5
  exclusions:
    warn-unused: true
    presets:
    - std-error-handling
    - common-false-positives
