apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test-deployment
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args:
        - sleep
        - "10000"
        command:
        - /bin/bash
        - -c
        env: []
        image: busybox:latest
        imagePullPolicy: Always
        name: test-container
        ports: []
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 1000
      terminationGracePeriodSeconds: 60
