apiVersion: cuestomize.dev/v1alpha1
kind: Validator
metadata:
  name: example
  annotations:
    config.cuestomize.io/validator: "true" # tells the function to run as a validator
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/workday/cuestomize:latest
        network: true
includes:
# all deployments in the example-namespace namespace
- group: apps
  version: v1
  kind: Deployment
  namespace: example-namespace
remoteModule:
  registry: ghcr.io
  repo: workday/cuestomize/cuemodules/cuestomize-examples-validation
  tag: latest
