apiVersion: cuestomize.dev/v1alpha1
kind: Validator
metadata:
  name: example
  annotations:
    config.cuestomize.io/validator: "true" # tells the function to run as a validator
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/workday/cuestomize:latest
        network: true
includes:
- group: ""
  version: v1
- group: apps
  version: v1
- group: batch
  version: v1

remoteModule:
  ref: github.com/workday/cuestomize/cuemodules/cuestomize-examples-validation:latest
