name: CI (Dagger)

on:
  pull_request:
    types: [ review_requested, ready_for_review ]

jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: golangci-lint-run

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: test-with-coverage

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: e-2-e-test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build image
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: build

  publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Dagger Build And Publish
      uses: dagger/dagger-for-github@8.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        TAG: dev
        LATEST: "false"
        REPOSITORY: workday/cuestomize
      with:
        version: "0.18.14"
        verb: call
        args: build-and-publish --repository="$REPOSITORY" --tag="$TAG" --also-tag-as-latest="$LATEST" --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --platforms=linux/amd64,linux/arm64
