name: CI (Merge)

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build image
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: test-with-coverage

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: "0.18.14"
        verb: call
        args: e-2-e-test

  publish-examples:
    name: Publish Examples
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pipeline
      uses: dagger/dagger-for-github@8.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
      with:
        version: "0.18.14"
        verb: call
        args: |
          publish-examples --username="$GITHUB_USER" \
            --password=env:GITHUB_TOKEN
