name: Refresh Images

on:
  workflow_dispatch:
  schedule:
  - cron: "0 8 * * 1"

jobs:
  prep:
    name: Prepare
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
    - name: Get Latest Version
      id: get-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # get the latest version from the latest release, or use "nightly" if there are no releases
        VERSION=$(gh api "/repos/Workday/cuestomize/releases/latest" | jq -r '.tag_name')
        if [ -z "$VERSION" ] || [ "$VERSION" == "null" ]; then
          exit 1
        fi
        echo "Latest version: ${VERSION}"
        echo -n "version=${VERSION}" >> $GITHUB_OUTPUT

  refresh:
    name: Refresh Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: prep

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-tags: true

    - name: Dagger Build And Publish
      uses: dagger/dagger-for-github@v8.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        VERSION: ${{ needs.prep.outputs.version }}
        LATEST: "true"
        REPOSITORY: "workday/cuestomize"
        PLATFORMS: "linux/amd64,linux/arm64"
      with:
        version: "0.20.5"
        verb: call
        args: build-and-publish --repository="$REPOSITORY" --ref="$VERSION" --version="$VERSION" --latest="$LATEST" --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --platforms="$PLATFORMS"
