name: Release

on:
  release:
    types: [ published, prereleased ]

jobs:
  prep:
    name: Prepare
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.release.tag_name }}

    outputs:
      version: ${{ steps.get-version.outputs.version }}
      latest: ${{ steps.set-latest.outputs.latest }}

    steps:
    - name: Version Follows SemVer
      run: |
        if [[ ! "${TAG}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[\w.]+)?$ ]]; then
          echo "Invalid SemVer: ${TAG}" >&2
          exit 1
        fi

    - name: Get Version
      id: get-version
      run: |
        VERSION=${TAG}

        echo -n "version=${VERSION}" >> $GITHUB_OUTPUT

    # only tag as latest if the release is set to latest
    - name: set tag as latest
      id: set-latest
      run: |
        LATEST="false"
        if [ "${{ github.event.release.prerelease }}" == "false" ]; then
          LATEST="true"
        fi
        echo -n "latest=${LATEST}" >> $GITHUB_OUTPUT

  publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: prep

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Dagger Build And Publish
      uses: dagger/dagger-for-github@v8.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        VERSION: ${{ needs.prep.outputs.version }}
        LATEST: ${{ needs.prep.outputs.latest }}
        REPOSITORY: workday/cuestomize
      with:
        version: "0.20.3"
        verb: call
        args: build-and-publish --repository="$REPOSITORY" --version="$VERSION" --latest="$LATEST" --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --platforms=linux/amd64,linux/arm64

  publish-examples:
    name: Publish Examples
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: prep

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run pipeline
      uses: dagger/dagger-for-github@v8.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        REPOSITORY_PREFIX: ${{ github.repository }}/cuemodules/cuestomize-examples
        VERSION: ${{ needs.prep.outputs.version }}
        LATEST: ${{ needs.prep.outputs.latest }}
      with:
        version: "0.20.3"
        verb: call
        args: publish-examples --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --version="$VERSION" --latest="$LATEST" --repositoryPrefix="$REPOSITORY_PREFIX"
