name: Release

on:
  release:
    types: [ published, prereleased ]

jobs:
  prep:
    name: Prepare
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.generate-tag-name.outputs.TAG_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Tag Name
      id: generate-tag-name
      run: |
        # remove v prefix
        TAG=${{ github.event.release.tag_name }}
        TAG=${TAG#v}

        echo ${{ github.event.release.tag_name }}' >> $GITHUB_OUTPUT

    # only tag as latest if the release is set to latest
    - name: set tag as latest
      if: "!github.event.release.prerelease"
      run: echo -n 'true' >> $GITHUB_OUTPUT

  publish:
    name: Build And Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Dagger Build And Publish
      uses: dagger/dagger-for-github@8.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        TAG: ${{ needs.prep.outputs.tag_name }}
      with:
        version: "0.18.14"
        verb: call
        args: |
          build-and-publish --repository=workday/customize \
            --tag={{ TAG }} \
            --username=${{ github.actor }} --password=env:GITHUB_TOKEN \
